import{useEffect,useState}from'react';import{Link}from'react-router-dom';import{BriefcaseBusiness,FileUser,UserCheck,Trophy,Activity}from'lucide-react';import api from'../services/api';import{useAuth}from'../context/AuthContext';import{Loader,Empty,Status}from'../components/UI';
const initialStats={totalJobs:0,activeJobs:0,totalApplicants:0,shortlisted:0,hired:0};
export default function Dashboard(){
  const{user}=useAuth();const[rows,setRows]=useState();const[stats,setStats]=useState(initialStats);const[error,setError]=useState('');const recruiter=user.role==='recruiter';
  const load=async()=>{try{setError('');if(recruiter){const[jobsResponse,statsResponse]=await Promise.all([api.get('/jobs/mine'),api.get('/jobs/stats')]);setRows(jobsResponse.data.jobs);setStats(statsResponse.data.stats)}else{const response=await api.get('/applications/mine');setRows(response.data.applications)}}catch(requestError){setError(requestError.message)}};
  useEffect(()=>{load()},[]);
  const remove=async id=>{if(!confirm('Delete this job and all its applications? This cannot be undone.'))return;try{await api.delete(`/jobs/${id}`);await load()}catch(requestError){setError(requestError.message)}};
  if(!rows)return <Loader/>;
  const statCards=[{label:'Total jobs',value:stats.totalJobs,icon:BriefcaseBusiness},{label:'Active jobs',value:stats.activeJobs,icon:Activity},{label:'Applicants',value:stats.totalApplicants,icon:FileUser},{label:'Shortlisted',value:stats.shortlisted,icon:UserCheck},{label:'Hired',value:stats.hired,icon:Trophy}];
  return <main className="page container"><div className="dashboard-head"><div><span className="eyebrow">{recruiter?'RECRUITER WORKSPACE':'YOUR JOB SEARCH'}</span><h1>Welcome back, {user.name.split(' ')[0]}</h1><p>{recruiter?'Manage openings and move promising candidates forward.':'Keep your opportunities and progress in one place.'}</p></div>{recruiter&&<Link className="btn" to="/jobs/new">Post a job</Link>}</div>{error&&<div className="alert error">{error}</div>}{recruiter&&<section className="stats-grid">{statCards.map(({label,value,icon:Icon})=><article className="stat-card" key={label}><span className="stat-icon"><Icon/></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</section>}{!rows.length?<Empty title={recruiter?'No jobs posted yet':'No applications yet'} text={recruiter?'Create your first opening to start meeting candidates.':'Explore jobs and submit your first application.'}/>:recruiter?<div className="table-wrap"><table><thead><tr><th>Role</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(job=><tr key={job._id}><td><strong>{job.title}</strong><small>{job.company}</small></td><td>{job.location} · {job.workMode}</td><td><Status value={job.status}/></td><td className="actions"><Link to={`/jobs/${job._id}/edit`}>Edit</Link><Link to={`/jobs/${job._id}/applicants`}>Applicants</Link><button onClick={()=>remove(job._id)}>Delete</button></td></tr>)}</tbody></table></div>:<div className="table-wrap"><table><thead><tr><th>Position</th><th>Location</th><th>Applied</th><th>Status</th></tr></thead><tbody>{rows.map(application=><tr key={application._id}><td><Link to={`/jobs/${application.job?._id}`}><strong>{application.job?.title}</strong></Link><small>{application.job?.company}</small></td><td>{application.job?.location}</td><td>{new Date(application.createdAt).toLocaleDateString()}</td><td><Status value={application.status}/></td></tr>)}</tbody></table></div>}</main>;
}
